ADD requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt
RUN apt-get install -y libcupti-dev mlocate
RUN updatedb
RUN cd /src && git clone https://github.com/tensorflow/tensorflow.git
#v1.3.0
RUN cd /src/tensorflow && git checkout 9e76bf324f6bac63137a02bb6e6ec9120703ea9b
ADD tensorflow_configure_resp_1.3.0 /tmp
RUN cd /src/tensorflow && ./configure < /tmp/tensorflow_configure_resp_1.3.0
#RUN cd /src/tensorflow && bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
#RUN bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
#RUN pip install /tmp/tensorflow_pkg/tensorflow-1.3.0-py2-none-any.whl

#nvidia-docker build -f docker/Dockerfile -t registry.coneptum.com:443/coneptum/ullclinic:latest .
